version: '3.7'
services:
  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    #depends_on:
    #  - cadvisor
    networks:
      - t2_proxy
    #  - monitor-net
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - "${_HYPERION_ALERTMANAGER_PORT_HTTP_PUBLISHED}:${_HYPERION_ALERTMANAGER_PORT_HTTP_TARGET}"
    #expose:
    #  - ${_HYPERION_ALERTMANAGER_PORT_HTTP_TARGET}
    volumes:
      - ${_HYPERION_STORAGE_SRV_CONFIG}/alertmanager:/etc/alertmanager
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.alertmanager-svc.loadbalancer.server.port=${_HYPERION_ALERTMANAGER_PORT_HTTP_TARGET}"

      #-> WAN\HTTP Routers
      - "traefik.http.routers.alertmanager-wan-rtr.entrypoints=https"
      - "traefik.http.routers.alertmanager-wan-rtr.rule=Host(`${_HYPERION_ALERTMANAGER_WAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_WAN_DOMAIN}`)"
      - "traefik.http.routers.alertmanager-wan-rtr.tls=true"
      #-> WAN\Middlewares
      - "traefik.http.routers.alertmanager-wan-rtr.middlewares=chain-oauth@file"
      #-> WAN\HTTP Services
      - "traefik.http.routers.alertmanager-wan-rtr.service=alertmanager-svc"

      #-> LAN\HTTP Routers
      - "traefik.http.routers.alertmanager-lan-rtr.entrypoints=http"
      - "traefik.http.routers.alertmanager-lan-rtr.rule=Host(`${_HYPERION_ALERTMANAGER_LAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_LAN_DOMAIN}`)"
      #-> LAN\Middlewares
      #- "traefik.http.routers.alertmanager-lan-rtr.middlewares=chain-oauth@file"
      #-> LAN\HTTP Services
      - "traefik.http.routers.alertmanager-lan-rtr.service=alertmanager-svc"
