version: '3.7'
services:
  #-> https://hub.docker.com/r/salihciftci/liman/
  liman:
    image: salihciftci/liman
    container_name: liman
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - "${_HYPERION_LIMAN_PORT_HTTP_PUBLISHED}:${_HYPERION_LIMAN_PORT_HTTP_TARGET}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${_HYPERION_STORAGE_DATA}/liman/data:/liman/data
      #- "liman:/liman/data"
    #environment:
    #  - PUID=${_HYPERION_UID}
    #  - PGID=${_HYPERION_GID}
    #  - TZ=${_HYPERION_TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.liman-svc.loadbalancer.server.port=${_HYPERION_LIMAN_PORT_HTTP_TARGET}"

      #-> WAN\HTTP Routers
      - "traefik.http.routers.liman-wan-rtr.entrypoints=https"
      - "traefik.http.routers.liman-wan-rtr.rule=Host(`${_HYPERION_LIMAN_WAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_WAN_DOMAIN}`)"
      - "traefik.http.routers.liman-wan-rtr.tls=true"
      #-> WAN\Middlewares
      - "traefik.http.routers.liman-wan-rtr.middlewares=chain-oauth@file"
      #-> WAN\HTTP Services
      - "traefik.http.routers.liman-wan-rtr.service=liman-svc"

      #-> LAN\HTTP Routers
      - "traefik.http.routers.liman-lan-rtr.entrypoints=http"
      - "traefik.http.routers.liman-lan-rtr.rule=Host(`${_HYPERION_LIMAN_LAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_LAN_DOMAIN}`)"
      #-> LAN\Middlewares
      #- "traefik.http.routers.liman-lan-rtr.middlewares=chain-oauth@file"
      #-> LAN\HTTP Services
      - "traefik.http.routers.liman-lan-rtr.service=liman-svc"
