version: '3.7'
services:
  #-> https://hub.docker.com/r/sematext/agent/
  sematext-agent:
    image: sematext/agent:latest
    container_name: sematext-agent
    restart: always
    cap_add:
      - SYS_ADMIN
    #privileged: true
    #security_opt:
    #  - no-new-privileges: true
    volumes:
        - '/:/hostfs:ro'
        - '/sys/:/hostfs/sys:ro'
        - '/var/run/:/var/run/'
        - '/sys/kernel/debug:/sys/kernel/debug'
        - '/etc/passwd:/etc/passwd:ro'
        - '/etc/group:/etc/group:ro'
    environment:
      - CONTAINER_TOKEN=${_HYPERION_SECRETS_SEMATEXT_AGENT_CONTAINER_TOKEN}
      - INFRA_TOKEN=${_HYPERION_SECRETS_SEMATEXT_AGENT_INFRA_TOKEN}
      - NODE_NAME=${_HYPERION_HOSTNAME}
      - REGION=${_HYPERION_SEMATEXT_AGENT_REGION}
