version: "3.3"
services:
  #-> https://hub.docker.com/r/organizrtools/organizr-v2/
  organizr:
    image: organizrtools/organizr-v2:plex
    container_name: organizr
    restart: unless-stopped
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
    volumes:
      - ${_HYPERION_DATA}/organizr/config:/config
      #?- ${_HYPERION_DATA}/shared:/shared
    ports:
      - ${_HYPERION_ORGANIZR_PORT}:80
  #-> https://hub.docker.com/r/plexinc/pms-docker
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    hostname: ${_HYPERION_HOSTNAME}
    environment:
      - TZ=${_HYPERION_TIMEZONE}
      - PLEX_UID=${_HYPERION_UID}
      - PLEX_GID=${_HYPERION_GID}
      #?- ADVERTISE_IP="http://192.168.0.0:32400/"
    volumes:
      - ${_HYPERION_DATA}/plex/config:/config
      - ${_HYPERION_DATA}/acme-cert:/cert
      - ${_HYPERION_TMP}/plex/transcode:/transcode
      - ${_HYPERION_MULTIMEDIA}:/data
      #?- ${USERDIR}/docker/plexms:/config
      #?- ${USERDIR}/Downloads/plex_tmp:/transcode
      #?#Where all your media is stored
      #?- /media/USER:/media
      #?- ${USERDIR}/docker/shared:/shared
      #?- ${USERDIR}/docker/letsencryptcerts:/certs:ro
    ports:
      - ${_HYPERION_PLEX_PORT}:32400/tcp # PRIMARY_TCP
      - ${_HYPERION_PLEX_WEBTOOLS_PORT}:33400/tcp # WebTools plugin
      - 3005:3005/tcp # COMPANION_TCP
      - 8324:8324/tcp # COMPANION_ROKU_TCP
      - 32469:32469/tcp # DLNA_TCP
      - 1900:1900/udp # DLNA_UDP
      - 32410:32410/udp # NETWORK_DISCOVERY_1_UDP
      - 32412:32412/udp # NETWORK_DISCOVERY_2_UDP
      - 32413:32413/udp # NETWORK_DISCOVERY_3_UDP
      - 32414:32414/udp # NETWORK_DISCOVERY_4_UDP
  #-> https://hub.docker.com/r/linuxserver/ombi
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    #hostname: hyperion-ombi
    #+ depends_on:
    #+   - jackett
    #+   - qbittorrent
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
    volumes:
      - ${_HYPERION_DATA}/ombi/config:/config
      #?- ${_HYPERION_DATA}/shared:/shared
    ports:
      - ${_HYPERION_OMBI_PORT}:3579
  #-> https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - jackett
      - qbittorrent
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
      #?- UMASK_SET=022 #optional
    volumes:
      - ${_HYPERION_DATA}/sonarr/config:/config
      - ${_HYPERION_MULTIMEDIA}:/multimedia
    ports:
      - ${_HYPERION_SONARR_PORT}:8989
  #-> https://hub.docker.com/r/linuxserver/radarr
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - jackett
      - qbittorrent
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
      #?- UMASK_SET=022 #optional
    volumes:
      - ${_HYPERION_DATA}/radarr/config:/config
      - ${_HYPERION_MULTIMEDIA}:/multimedia
    ports:
      - ${_HYPERION_RADARR_PORT}:7878
  #-> https://hub.docker.com/r/linuxserver/qbittorrent
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
      - WEBUI_PORT=${_HYPERION_QBITTORRENT_PORT_WEBUI}
      #?- UMASK_SET=022
    volumes:
      - ${_HYPERION_DATA}/qbittorrent/config:/config
      - ${_HYPERION_MULTIMEDIA}/downloads:/downloads
    ports:
      - ${_HYPERION_QBITTORRENT_PORT_TCP}:6881
      - ${_HYPERION_QBITTORRENT_PORT_UDP}:6881/udp
      - ${_HYPERION_QBITTORRENT_PORT_WEBUI}:${_HYPERION_QBITTORRENT_PORT_WEBUI}
  #-> https://hub.docker.com/r/linuxserver/jackett/
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
      #?- RUN_OPTS=run options here #optional
    volumes:
      - ${_HYPERION_DATA}/jackett/config:/config
      #?- path to blackhole:/downloads
    ports:
      - ${_HYPERION_JACKETT_PORT}:9117
  #-> https://hub.docker.com/r/linuxserver/tautulli
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    #+ depends_on:
    #+   - plex???
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
    volumes:
      - ${_HYPERION_DATA}/tautulli/config:/config
      - ${_HYPERION_DATA}/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
      #- ${_HYPERION_DATA}/shared:/shared
    ports:
      - ${_HYPERION_TAUTULLI_PORT}:8181
