version: '3.7'
# Autoindex - Simple Directory Index
services:
  #-> https://hub.docker.com/r/dceoy/nginx-autoindex/
  autoindex:
    image: dceoy/nginx-autoindex:latest
    container_name: autoindex
    restart: always
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - "${_HYPERION_AUTOINDEX_PORT_HTTP_PUBLISHED}:${_HYPERION_AUTOINDEX_PORT_HTTP_TARGET}"
    volumes:
      - ${_HYPERION_STORAGE_MULTIMEDIA}:/var/lib/nginx/html:ro # Location you want to index
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.autoindex-svc.loadbalancer.server.port=${_HYPERION_AUTOINDEX_PORT_HTTP_TARGET}"

      #-> WAN\HTTP Routers
      - "traefik.http.routers.autoindex-wan-rtr.entrypoints=https"
      - "traefik.http.routers.autoindex-wan-rtr.rule=Host(`${_HYPERION_AUTOINDEX_WAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_WAN_DOMAIN}`)"
      - "traefik.http.routers.autoindex-wan-rtr.tls=true"
      #-> WAN\Middlewares
      - "traefik.http.routers.autoindex-wan-rtr.middlewares=chain-oauth@file"
      #-> WAN\HTTP Services
      - "traefik.http.routers.autoindex-wan-rtr.service=autoindex-svc"

      #-> LAN\HTTP Routers
      - "traefik.http.routers.autoindex-lan-rtr.entrypoints=http"
      - "traefik.http.routers.autoindex-lan-rtr.rule=Host(`${_HYPERION_AUTOINDEX_LAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_LAN_DOMAIN}`)"
      #-> LAN\Middlewares
      #- "traefik.http.routers.autoindex-lan-rtr.middlewares=chain-oauth@file"
      #-> LAN\HTTP Services
      - "traefik.http.routers.autoindex-lan-rtr.service=autoindex-svc"
