# Organizr - Unified Frontend
services:
  #-> https://hub.docker.com/r/organizrtools/organizr-v2/
  organizr:
    image: organizrtools/organizr-v2:plex
    container_name: organizr
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - ${_HYPERION_ORGANIZR_PORT_HTTP_PUBLISHED}:${_HYPERION_ORGANIZR_PORT_HTTP_TARGET}
    volumes:
      - ${_HYPERION_STORAGE_DATA}/organizr/config:/config
      - ${_HYPERION_STORAGE_DATA}/shared:/shared
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.organizr-rtr.entrypoints=https"
      - "traefik.http.routers.organizr-rtr.rule=Host(`${_HYPERION_ORGANIZR_WAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_WAN_DOMAIN}`)"
      - "traefik.http.routers.organizr-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.organizr-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.organizr-rtr.service=organizr-svc"
      - "traefik.http.services.organizr-svc.loadbalancer.server.port=${_HYPERION_ORGANIZR_PORT_HTTP_TARGET}"
