version: '3.7'
services:
  #-> https://hub.docker.com/r/portainer/portainer/
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - "${_HYPERION_PORTAINER_PORT_HTTP_PUBLISHED}:${_HYPERION_PORTAINER_PORT_HTTP_TARGET}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${_HYPERION_STORAGE_DATA}/portainer/data:/data # Change to local directory if you want to save/transfer config locally
    environment:
      - TZ=${_HYPERION_TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=${_HYPERION_PORTAINER_PORT_HTTP_TARGET}"

      #-> WAN\HTTP Routers
      - "traefik.http.routers.portainer-wan-rtr.entrypoints=https"
      - "traefik.http.routers.portainer-wan-rtr.rule=Host(`${_HYPERION_PORTAINER_WAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_WAN_DOMAIN}`)"
      - "traefik.http.routers.portainer-wan-rtr.tls=true"
      #-> WAN\Middlewares
      #- "traefik.http.routers.portainer-wan-rtr.middlewares=chain-no-auth@file" # No Authentication
      #- "traefik.http.routers.portainer-wan-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      - "traefik.http.routers.portainer-wan-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      #-> WAN\HTTP Services
      - "traefik.http.routers.portainer-wan-rtr.service=portainer-svc"

      #-> LAN\HTTP Routers
      - "traefik.http.routers.portainer-lan-rtr.entrypoints=http"
      - "traefik.http.routers.portainer-lan-rtr.rule=Host(`${_HYPERION_PORTAINER_LAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_LAN_DOMAIN}`)"
      #-> LAN\Middlewares
      #- "traefik.http.routers.portainer-lan-rtr.middlewares=chain-no-auth@file" # No Authentication
      #- "traefik.http.routers.portainer-lan-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      #- "traefik.http.routers.portainer-lan-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      #-> LAN\HTTP Services
      - "traefik.http.routers.portainer-lan-rtr.service=portainer-svc"
