#-> https://hub.docker.com/r/linuxserver/lazylibrarian
version: "3.3"
services:
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/lazylib/config:/config
      #External Mount (The torrent downloader plays friendly when theyre the same directories inside each container)
      #Remember this can be changed to ${USERDIR}/docker/downloads/books:/downloads/books
      #Remember this can be changed to ${USERDIR}/docker/downloads/audiobooks:/downloads/audiobooks
      - /media/USER/HDD/books:/downloads/books
      - /media/USER/HDD/audiobooks:/downloads/audiobooks
      - ${USERDIR}/media/media/books:/books
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 5299:5299
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    #+ depends_on:
    #+   - jackett
    #+   - qbittorrent
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
      #?- UMASK_SET=022 #optional
    volumes:
      - ${_HYPERION_DATA}/radarr/config:/config
      - ${_HYPERION_MULTIMEDIA}:/multimedia
    ports:
      - ${_HYPERION_RADARR_PORT}:7878
    networks:
      - proxy
    labels:
      caddy_1.tls: "off"
      caddy_1.address: ${_HYPERION_URL_BASE}/radarr
      caddy_1.targetport: ${_HYPERION_RADARR_PORT}
      caddy_1.proxy.transparent: ""
