# Ombi - Media Requests
services:
  #-> https://hub.docker.com/r/linuxserver/ombi
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    networks:
      - t2_proxy
    #ports:
    #  - "${_HYPERION_OMBI_PORT_HTTP_PUBLISHED}:${_HYPERION_OMBI_PORT_HTTP_TARGET}"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${_HYPERION_STORAGE_DATA}/ombi/config:/config
      - ${_HYPERION_STORAGE_DATA}/shared:/shared
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
      #- BASE_URL=/ombi #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ombi-svc.loadbalancer.server.port=${_HYPERION_OMBI_PORT_HTTP_TARGET}"

      #-> WAN\HTTP Routers
      - "traefik.http.routers.ombi-wan-rtr.entrypoints=https"
      - "traefik.http.routers.ombi-wan-rtr.rule=Host(`${_HYPERION_OMBI_WAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_WAN_DOMAIN}`)"
      - "traefik.http.routers.ombi-wan-rtr.tls=true"
      #-> WAN\Middlewares
      - "traefik.http.routers.ombi-wan-rtr.middlewares=chain-oauth@file"
      #-> WAN\HTTP Services
      - "traefik.http.routers.ombi-wan-rtr.service=ombi-svc"

      #-> LAN\HTTP Routers
      - "traefik.http.routers.ombi-lan-rtr.entrypoints=http"
      - "traefik.http.routers.ombi-lan-rtr.rule=Host(`${_HYPERION_OMBI_LAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_LAN_DOMAIN}`)"
      #-> LAN\Middlewares
      #- "traefik.http.routers.ombi-lan-rtr.middlewares=chain-oauth@file"
      #-> LAN\HTTP Services
      - "traefik.http.routers.ombi-lan-rtr.service=ombi-svc"