services:
  #-> https://hub.docker.com/prom/prometheus/
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      #- "--web.console.libraries=/usr/share/prometheus/console_libraries"
      #- "--web.console.templates=/usr/share/prometheus/consoles"
    depends_on:
      - cadvisor
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - "${_HYPERION_PROMETHEUS_PORT_HTTP_PUBLISHED}:${_HYPERION_PROMETHEUS_PORT_HTTP_TARGET}"
    volumes:
      #- ${_HYPERION_STORAGE_DATA}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      #- ${_HYPERION_STORAGE_DATA}/prometheus/etc:/etc/prometheus
      #- ${_HYPERION_STORAGE_DATA}/prometheus/data:/prometheus
      - ${_HYPERION_STORAGE_DATA}/prometheus/var/lib:/var/lib/prometheus
      #- ${_HYPERION_STORAGE_DATA}/shared:/shared
