# Tautulli - Previously PlexPy. Plex statistics and monitoring
# Set HTTP Root in Tautulli settings if using PathPrefix
services:
  #-> https://hub.docker.com/r/linuxserver/tautulli
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    #depends_on:
    #  - plex???
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    #ports:
    #  - "${_HYPERION_TAUTULLI_PORT_HTTP_PUBLISHED}:${_HYPERION_TAUTULLI_PORT_HTTP_TARGET}"
    volumes:
      - ${_HYPERION_STORAGE_DATA}/tautulli/config:/config
      - ${_HYPERION_STORAGE_DATA}/plexms/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
      - ${_HYPERION_STORAGE_DATA}/shared:/shared
    environment:
      - PUID=${_HYPERION_UID}
      - PGID=${_HYPERION_GID}
      - TZ=${_HYPERION_TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=${_HYPERION_TAUTULLI_PORT_HTTP_TARGET}"

      #-> WAN\HTTP Routers
      - "traefik.http.routers.tautulli-wan-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-wan-rtr.rule=Host(`${_HYPERION_TAUTULLI_WAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_WAN_DOMAIN}`)"
      - "traefik.http.routers.tautulli-wan-rtr.tls=true"
      #-> WAN\Middlewares
      - "traefik.http.routers.tautulli-wan-rtr.middlewares=chain-oauth@file"
      #-> WAN\HTTP Services
      - "traefik.http.routers.tautulli-wan-rtr.service=tautulli-svc"

      #-> LAN\HTTP Routers
      - "traefik.http.routers.tautulli-lan-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-lan-rtr.rule=Host(`${_HYPERION_TAUTULLI_LAN_DOMAIN_PREFIX}${_HYPERION_NETWORK_LAN_DOMAIN}`)"
      #-> LAN\Middlewares
      #- "traefik.http.routers.tautulli-lan-rtr.middlewares=chain-oauth@file"
      #-> LAN\HTTP Services
      - "traefik.http.routers.tautulli-lan-rtr.service=tautulli-svc"
